"""Create initial schema for review management

Revision ID: 87e9b654863c
Revises: 
Create Date: 2025-08-07 14:36:40.356236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87e9b654863c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewed_objects',
    sa.Column('object_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('object_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('object_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('object_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type', 'object_id', name='uq_object_type_id')
    )
    op.create_index(op.f('ix_reviewed_objects_object_type'), 'reviewed_objects', ['object_type'], unique=False)
    op.create_table('reviewers',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewers_email'), 'reviewers', ['email'], unique=True)
    op.create_index(op.f('ix_reviewers_username'), 'reviewers', ['username'], unique=True)
    op.create_table('reviews',
    sa.Column('text_review', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('thumbs_rating', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_object_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("thumbs_rating IN ('up', 'down') OR thumbs_rating IS NULL", name='check_thumbs_rating_values'),
    sa.CheckConstraint('star_rating >= 0 AND star_rating <= 5', name='check_star_rating_range'),
    sa.CheckConstraint('text_review IS NOT NULL OR star_rating IS NOT NULL OR thumbs_rating IS NOT NULL', name='check_review_content_exists'),
    sa.ForeignKeyConstraint(['reviewed_object_id'], ['reviewed_objects.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reviewer_id', 'reviewed_object_id', name='uq_reviewer_object')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reviewers_username'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_email'), table_name='reviewers')
    op.drop_table('reviewers')
    op.drop_index(op.f('ix_reviewed_objects_object_type'), table_name='reviewed_objects')
    op.drop_table('reviewed_objects')
    # ### end Alembic commands ###
