name: Codespaces Prebuild

on:
  push:
    branches: [main]
    paths: 
      - '.devcontainer/**'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches: [main]
    paths: 
      - '.devcontainer/**'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  prebuild:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'krzysztofkucmierz'
    steps:
      - name: Prebuild Codespaces
        uses: github/codespaces-prebuild@v1
        with:
          devcontainer_file: .devcontainer/devcontainer.json
